name: strandersson

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

domains:
- domain: strandersson.se
  type: PRIMARY
  zone: strandersson.se
- domain: www.strandersson.se
  type: ALIAS
  zone: strandersson.se

ingress: {}

region: ams

static_sites:
- name: strandersson-static
  github:
    repo: johan-st/strandersson.se
    branch: master
    deploy_on_push: true
  source_dir: /
  dockerfile_path: /Dockerfile
  output_dir: /dist
  catchall_document: index.html
  routes:
  - path: /