alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

domains:
- domain: strandersson.se
  type: PRIMARY
  zone: strandersson.se
- domain: www.strandersson.se
  type: ALIAS
  zone: strandersson.se

ingress:
  rules:
  - component:
      name: strandersson-static
    match:
      path:
        prefix: /

name: strandersson

region: ams

static_sites:
- catchall_document: index.html
  environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: johan-st/strandersson.se
  name: strandersson-static
  source_dir: dist
