alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: strandersson.se
  type: PRIMARY
  zone: strandersson.se
- domain: www.strandersson.se
  type: ALIAS
  zone: strandersson.se
ingress: {}
name: strandersson
region: ams
static_sites:
- build_command: hugo
  dir: dist
  catchall_document: index.html
  build_command: npm run build
  output_dir: dist
  github:
    repo: strandersson/strandersson.se
    branch: master
    deploy_on_push: true

# services:
# - http_port: 80
#   image:
#     deploy_on_push:
#       enabled: true
#     registry_type: DOCR
#     repository: strandersson
#     tag: latest
#   instance_count: 1
#   instance_size_slug: basic-xxs
#   name: strandersson
#   routes:
#   - path: /
